accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("registration/", views.registration_view, name="registration")
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("pages.urls")),
    path("accounts/", include("accounts.urls"))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name = "main"
# {% url 'main:home' %}
urlpatterns = [
    path("", views.home_view, name="home"),
    path("categories/", views.shop_view, name="shop"),
    path("categories/<slug:slug>/", views.subcategory_products_view, name="subcategory_products"),
    path("products/<slug:slug>/", views.product_detail, name="product_detail")
]

accounts/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

# Create your models here.


class Category(models.Model):
    name = models.CharField(verbose_name="Название категории", max_length=150, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Subcategory(models.Model):
    name = models.CharField(verbose_name="Название подкатегории", max_length=150, unique=True)
    slug = models.SlugField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Категория",
                                 related_name="categories")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("main:subcategory_products", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Подкатегория"
        verbose_name_plural = "Подкатегории"


class Product(models.Model):
    PRODUCT_TYPES = (
        ("new", "New"),
        ("sale", "Sale"),
        ("sold", "Sold"),
    )

    title = models.CharField(verbose_name="Название товара", max_length=150, unique=True)
    descr = models.TextField(verbose_name="Описание товара")
    price = models.IntegerField(verbose_name="Цена товара")
    quantity = models.IntegerField(verbose_name="Кол-во товара", default=10)
    product_type = models.CharField(verbose_name="Тип продукта", choices=PRODUCT_TYPES, max_length=4)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE, blank=True, null=True)
    slug = models.SlugField(unique=True)

    def get_absolute_url(self):
        return reverse("main:product_detail", kwargs={"slug": self.slug})

    def get_class_by_type(self):
        types = {
            "new": "info",
            "sale": "primary",
            "sold": "danger"
        }
        return types[self.product_type]

    def get_first_photo(self):
        photo = self.productimage_set.all().first()
        if photo is not None:
            return photo.photo.url
        return "https://images.satu.kz/126101312_w640_h640_razdel-v-razrabotketovary.jpg"


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class ProductImage(models.Model):
    photo = models.ImageField(verbose_name="Фото", upload_to="products/", null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

# телефон самсунг telefon-samsung

accounts/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.


def login_view(request):
    return HttpResponse("login page")


def registration_view(request):
    return HttpResponse("registration page")

pages/views.py
from django.shortcuts import render, HttpResponse
from .models import Product, Subcategory
from django.core.paginator import Paginator

# Create your views here.


def home_view(request):
    return render(request, "pages/index.html")


def shop_view(request):
    products = Product.objects.all()
    paginator = Paginator(products, 1)
    page = request.GET.get("page")
    result = paginator.get_page(page)

    context = {
        "products": result
    }
    return render(request, "pages/shop.html", context)


def subcategory_products_view(request, slug):
    subcategory = Subcategory.objects.get(slug=slug)
    products = Product.objects.filter(subcategory=subcategory)
    context = {
        "products": products
    }
    return render(request, "pages/shop.html", context)


def product_detail(request, slug):
    product = Product.objects.get(slug=slug)
    related_products = Product.objects.filter(category=product.category)
    context = {
        "product_detail": product,
        "related_products": related_products
    }
    return render(request, "pages/product_detail.html", context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- gLightbox gallery-->
    <link rel="stylesheet" href="{% static 'vendor/glightbox/css/glightbox.min.css' %}">
    <!-- Range slider-->
    <link rel="stylesheet" href="{% static 'vendor/nouislider/nouislider.min.css' %}">
    <!-- Choices CSS-->
    <link rel="stylesheet" href="{% static 'vendor/choices.js/public/assets/styles/choices.min.css' %}">
    <!-- Swiper slider-->
    <link rel="stylesheet" href="{% static 'vendor/swiper/swiper-bundle.min.css' %}">
    <!-- Google fonts-->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@300;400;700&amp;display=swap">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Martel+Sans:wght@300;400;800&amp;display=swap">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="img/favicon.png">
</head>
<body>
<div class="page-holder">
    <!-- navbar-->
    <header class="header bg-white">
        <div class="container px-lg-3">
            <nav class="navbar navbar-expand-lg navbar-light py-3 px-lg-0"><a class="navbar-brand"
                                                                              href="{% url 'main:home' %}"><span
                    class="fw-bold text-uppercase text-dark">Boutique</span></a>
                <button class="navbar-toggler navbar-toggler-end" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <!-- Link--><a class="nav-link active" href="{% url 'main:home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <!-- Link--><a class="nav-link" href="{% url 'main:shop' %}">Shop</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="cart.html"> <i
                                class="fas fa-dolly-flatbed me-1 text-gray"></i>Cart<small class="text-gray fw-normal">(2)</small></a>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="#!"> <i class="far fa-heart me-1"></i><small
                                class="text-gray fw-normal"> (0)</small></a></li>
                        {% if not request.user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}"> <i
                                class="fas fa-user me-1 text-gray fw-normal"></i>Login</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="#"> <i
                                class="fas fa-user me-1 text-gray fw-normal"></i>Logout</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    <!--  Modal -->

    <!-- HERO SECTION-->
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

    <footer class="bg-dark text-white">
        <div class="container py-4">
            <div class="row py-5">
                <div class="col-md-4 mb-3 mb-md-0">
                    <h6 class="text-uppercase mb-3">Customer services</h6>
                    <ul class="list-unstyled mb-0">
                        <li><a class="footer-link" href="#!">Help &amp; Contact Us</a></li>
                        <li><a class="footer-link" href="#!">Returns &amp; Refunds</a></li>
                        <li><a class="footer-link" href="#!">Online Stores</a></li>
                        <li><a class="footer-link" href="#!">Terms &amp; Conditions</a></li>
                    </ul>
                </div>
                <div class="col-md-4 mb-3 mb-md-0">
                    <h6 class="text-uppercase mb-3">Company</h6>
                    <ul class="list-unstyled mb-0">
                        <li><a class="footer-link" href="#!">What We Do</a></li>
                        <li><a class="footer-link" href="#!">Available Services</a></li>
                        <li><a class="footer-link" href="#!">Latest Posts</a></li>
                        <li><a class="footer-link" href="#!">FAQs</a></li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <h6 class="text-uppercase mb-3">Social media</h6>
                    <ul class="list-unstyled mb-0">
                        <li><a class="footer-link" href="#!">Twitter</a></li>
                        <li><a class="footer-link" href="#!">Instagram</a></li>
                        <li><a class="footer-link" href="#!">Tumblr</a></li>
                        <li><a class="footer-link" href="#!">Pinterest</a></li>
                    </ul>
                </div>
            </div>
            <div class="border-top pt-4" style="border-color: #1d1d1d !important">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start">
                        <p class="small text-muted mb-0">&copy; 2021 All rights reserved.</p>
                    </div>
                    <div class="col-md-6 text-center text-md-end">
                        <p class="small text-muted mb-0">Template designed by <a class="text-white reset-anchor"
                                                                                 href="https://bootstrapious.com/p/boutique-bootstrap-e-commerce-template">Bootstrapious</a>
                        </p>
                        <!-- If you want to remove the backlink, please purchase the Attribution-Free License. See details in readme.txt or license.txt. Thanks!-->
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- JavaScript files-->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'vendor/nouislider/nouislider.min.js' %}"></script>
    <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'vendor/choices.js/public/assets/scripts/choices.min.js' %}"></script>
    <script src="{% static 'js/front.js' %}"></script>
    <script>
        // ------------------------------------------------------- //
        //   Inject SVG Sprite -
        //   see more here
        //   https://css-tricks.com/ajaxing-svg-sprite/
        // ------------------------------------------------------ //
        function injectSvgSprite(path) {

            var ajax = new XMLHttpRequest();
            ajax.open("GET", path, true);
            ajax.send();
            ajax.onload = function(e) {
            var div = document.createElement("div");
            div.className = 'd-none';
            div.innerHTML = ajax.responseText;
            document.body.insertBefore(div, document.body.childNodes[0]);
            }
        }
        // this is set to BootstrapTemple website as you cannot
        // inject local SVG sprite (using only 'icons/orion-svg-sprite.svg' path)
        // while using file:// protocol
        // pls don't forget to change to your domain :)
        injectSvgSprite('https://bootstraptemple.com/files/icons/orion-svg-sprite.svg');


    </script>
    <!-- FontAwesome CSS - loading as last, so it doesn't block rendering-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</div>
</body>
</html>

templates/components/_modal.html
<div class="modal fade" id="modal-{{ product.pk }}" tabindex="-1">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content overflow-hidden border-0">
            <button class="btn-close p-4 position-absolute top-0 end-0 z-index-20 shadow-0" type="button"
                    data-bs-dismiss="modal" aria-label="Close"></button>
            <div class="modal-body p-0">
                <div class="row align-items-stretch">
                    <div class="col-lg-6 p-lg-0"><a class="glightbox product-view d-block h-100 bg-cover bg-center"
                                                    style="background: url({{ product.get_first_photo }})"
                                                    href="{{ product.get_first_photo }}" data-gallery="gallery-{{ product.pk }}"
                                                    data-glightbox="{{ product.title }}"></a>
                        {% for obj in product.productimage_set.all %}
                        {% if obj.photo.url != product.get_first_photo %}
                        <a class="glightbox d-none" href="{{ obj.photo.url }}"
                           data-gallery="gallery-{{ product.pk }}"
                           data-glightbox="{{ product.title }}"></a>
                        {% endif %}
                        {% endfor %}
                    </div>
                    <div class="col-lg-6">
                        <div class="p-4 my-md-4">
                            <ul class="list-inline mb-2">
                                <li class="list-inline-item m-0"><i class="fas fa-star small text-warning"></i></li>
                                <li class="list-inline-item m-0 1"><i class="fas fa-star small text-warning"></i>
                                </li>
                                <li class="list-inline-item m-0 2"><i class="fas fa-star small text-warning"></i>
                                </li>
                                <li class="list-inline-item m-0 3"><i class="fas fa-star small text-warning"></i>
                                </li>
                                <li class="list-inline-item m-0 4"><i class="fas fa-star small text-warning"></i>
                                </li>
                            </ul>
                            <h2 class="h4">{{ product.title }}</h2>
                            <p class="text-muted">${{ product.price }}</p>
                            <p class="text-sm mb-4">{{ product.descr }}</p>
                            <div class="row align-items-stretch mb-4 gx-0">
                                <div class="col-sm-7">
                                    <div class="border d-flex align-items-center justify-content-between py-1 px-3">
                                        <span class="small text-uppercase text-gray mr-4 no-select">Quantity</span>
                                        <div class="quantity">
                                            <button class="dec-btn p-0"><i class="fas fa-caret-left"></i></button>
                                            <input class="form-control border-0 shadow-0 p-0" type="text" value="1">
                                            <button class="inc-btn p-0"><i class="fas fa-caret-right"></i></button>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-5"><a
                                        class="btn btn-dark btn-sm w-100 h-100 d-flex align-items-center justify-content-center px-0"
                                        href="cart.html">Add to cart</a></div>
                            </div>
                            <a class="btn btn-link text-dark text-decoration-none p-0" href="#!"><i
                                    class="far fa-heart me-2"></i>Add to wish list</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/components/_pagination.html
{% if products.has_other_pages %}

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center justify-content-lg-end">
        {% if products.has_previous %}
        <li class="page-item mx-1"><a class="page-link" href="?page={{ products.previous_page_number }}" aria-label="Previous"><span
                aria-hidden="true">«</span></a></li>
        {% endif %}

        {% for i in products.paginator.page_range %}
        {% if products.number == i %}
        <li class="page-item mx-1 active"><a class="page-link">{{ i }}</a></li>
        {% else %}
        <li class="page-item mx-1"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}

        {% if products.has_next %}
        <li class="page-item ms-1"><a class="page-link" href="?page={{ products.next_page_number }}" aria-label="Next"><span
                aria-hidden="true">»</span></a></li>
        {% endif %}
    </ul>
</nav>

{% endif %}

templates/components/_product-card.html
{% load static %}


<div class="product text-center">
    <div class="mb-3 position-relative">
        {% if product.product_type %}
        <div class="badge text-white bg-{{ product.get_class_by_type }}">{{ product.product_type }}</div>
        {% endif %}
        <a class="d-block" href="{{ product.get_absolute_url }}">
            <img class="img-fluid w-100" src="{{ product.get_first_photo }}" alt="...">
        </a>
        <div class="product-overlay">
            <ul class="mb-0 list-inline">
                <li class="list-inline-item m-0 p-0"><a class="btn btn-sm btn-outline-dark"
                                                        href="#!"><i
                        class="far fa-heart"></i></a></li>
                <li class="list-inline-item m-0 p-0"><a class="btn btn-sm btn-dark"
                                                        href="cart.html">Add to cart</a></li>
                <li class="list-inline-item mr-0"><a class="btn btn-sm btn-outline-dark"
                                                     href="#modal-{{ product.pk }}" data-bs-toggle="modal"><i
                        class="fas fa-expand"></i></a></li>
            </ul>
        </div>
    </div>
    <h6><a class="reset-anchor" href="{{ product.get_absolute_url }}">{{ product.title }}</a></h6>
    <p class="small text-muted">${{ product.price }}</p>
</div>

{% include 'components/_modal.html' %}

templates/pages/product_detail.html
{% extends 'base.html' %}

{% block title %}
Продукт: {{ product_detail.title }}
{% endblock title %}


{% block content %}
<div class="row mb-5">
    <div class="col-lg-6">
        <!-- PRODUCT SLIDER-->
        <div class="row m-sm-0">
            <div class="col-sm-2 p-sm-0 order-2 order-sm-1 mt-2 mt-sm-0 px-xl-2">
                <div class="swiper product-slider-thumbs">
                    <div class="swiper-wrapper">
                        {% for obj in product_detail.productimage_set.all %}
                        <div class="swiper-slide h-auto swiper-thumb-item mb-3">
                            <img class="w-100" src="{{ obj.photo.url }}" alt="...">
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-sm-10 order-1 order-sm-2">
                <div class="swiper product-slider">
                    <div class="swiper-wrapper">
                        {% for obj in product_detail.productimage_set.all %}
                        <div class="swiper-slide h-auto"><a class="glightbox product-view"
                                                            href="{{ obj.photo.url }}" data-gallery="gallery-{{ product_detail.pk }}"
                                                            data-glightbox="Product item 1"><img class="img-fluid"
                                                                                                 src="{{ obj.photo.url }}"
                                                                                                 alt="..."></a></div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- PRODUCT DETAILS-->
    <div class="col-lg-6">
        <ul class="list-inline mb-2 text-sm">
            <li class="list-inline-item m-0"><i class="fas fa-star small text-warning"></i></li>
            <li class="list-inline-item m-0 1"><i class="fas fa-star small text-warning"></i></li>
            <li class="list-inline-item m-0 2"><i class="fas fa-star small text-warning"></i></li>
            <li class="list-inline-item m-0 3"><i class="fas fa-star small text-warning"></i></li>
            <li class="list-inline-item m-0 4"><i class="fas fa-star small text-warning"></i></li>
        </ul>
        <h1>{{ product_detail.title }}</h1>
        <p class="text-muted lead">${{ product_detail.price }}</p>
        <p class="text-sm mb-4">{{ product_detail.descr }}</p>
        <div class="row align-items-stretch mb-4">
            <div class="col-sm-5 pr-sm-0">
                <div class="border d-flex align-items-center justify-content-between py-1 px-3 bg-white border-white">
                    <span class="small text-uppercase text-gray mr-4 no-select">Quantity</span>
                    <div class="quantity">
                        <button class="dec-btn p-0"><i class="fas fa-caret-left"></i></button>
                        <input class="form-control border-0 shadow-0 p-0" type="text" value="1">
                        <button class="inc-btn p-0"><i class="fas fa-caret-right"></i></button>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 pl-sm-0"><a
                    class="btn btn-dark btn-sm btn-block h-100 d-flex align-items-center justify-content-center px-0"
                    href="cart.html">Add to cart</a></div>
        </div>
        <a class="text-dark p-0 mb-4 d-inline-block" href="#!"><i class="far fa-heart me-2"></i>Add to wish list</a><br>
        <ul class="list-unstyled small d-inline-block">
            <li class="px-3 py-2 mb-1 bg-white text-muted"><strong class="text-uppercase text-dark">Category:</strong><a
                    class="reset-anchor ms-2" href="{{ product_detail.subcategory.get_absolute_url }}">{{ product_detail.category }}</a></li>
        </ul>
    </div>
</div>
<!-- DETAILS TABS-->
<ul class="nav nav-tabs border-0" id="myTab" role="tablist">
    <li class="nav-item"><a class="nav-link text-uppercase active" id="description-tab" data-bs-toggle="tab"
                            href="#description" role="tab" aria-controls="description"
                            aria-selected="true">Description</a></li>
    <li class="nav-item"><a class="nav-link text-uppercase" id="reviews-tab" data-bs-toggle="tab" href="#reviews"
                            role="tab" aria-controls="reviews" aria-selected="false">Reviews</a></li>
</ul>
<div class="tab-content mb-5" id="myTabContent">
    <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="description-tab">
        <div class="p-4 p-lg-5 bg-white">
            <h6 class="text-uppercase">Product description </h6>
            <p class="text-muted text-sm mb-0">{{ product_detail.descr }}</p>
        </div>
    </div>
    <div class="tab-pane fade" id="reviews" role="tabpanel" aria-labelledby="reviews-tab">
        <div class="p-4 p-lg-5 bg-white">
            <div class="row">
                <div class="col-lg-8">
                    <div class="d-flex mb-3">
                        <div class="flex-shrink-0"><img class="rounded-circle" src="img/customer-1.png" alt=""
                                                        width="50"/></div>
                        <div class="ms-3 flex-shrink-1">
                            <h6 class="mb-0 text-uppercase">Jason Doe</h6>
                            <p class="small text-muted mb-0 text-uppercase">20 May 2020</p>
                            <ul class="list-inline mb-1 text-xs">
                                <li class="list-inline-item m-0"><i class="fas fa-star text-warning"></i></li>
                                <li class="list-inline-item m-0"><i class="fas fa-star text-warning"></i></li>
                                <li class="list-inline-item m-0"><i class="fas fa-star text-warning"></i></li>
                                <li class="list-inline-item m-0"><i class="fas fa-star text-warning"></i></li>
                                <li class="list-inline-item m-0"><i class="fas fa-star-half-alt text-warning"></i></li>
                            </ul>
                            <p class="text-sm mb-0 text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                                sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                    </div>
                    <div class="d-flex">
                        <div class="flex-shrink-0"><img class="rounded-circle" src="img/customer-2.png" alt=""
                                                        width="50"/></div>
                        <div class="ms-3 flex-shrink-1">
                            <h6 class="mb-0 text-uppercase">Jane Doe</h6>
                            <p class="small text-muted mb-0 text-uppercase">20 May 2020</p>
                            <ul class="list-inline mb-1 text-xs">
                                <li class="list-inline-item m-0"><i class="fas fa-star text-warning"></i></li>
                                <li class="list-inline-item m-0"><i class="fas fa-star text-warning"></i></li>
                                <li class="list-inline-item m-0"><i class="fas fa-star text-warning"></i></li>
                                <li class="list-inline-item m-0"><i class="fas fa-star text-warning"></i></li>
                                <li class="list-inline-item m-0"><i class="fas fa-star-half-alt text-warning"></i></li>
                            </ul>
                            <p class="text-sm mb-0 text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                                sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- RELATED PRODUCTS-->
<h2 class="h5 text-uppercase mb-4">Related products</h2>
<div class="row">
    <!-- PRODUCT-->
    {% for product in related_products %}
    <div class="col-lg-3 col-sm-6">
        {% include 'components/_product-card.html' %}
    </div>
    {% endfor %}
</div>
{% endblock content %}